"""baseline_v5_schema

Revision ID: 7b7fc2e4e158
Revises: 
Create Date: 2026-09-17 02:39:28.951152
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '7b7fc2e4e158'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auto_unseal_providers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('provider_type', sa.Enum('AWS_KMS', 'AZURE_KEY_VAULT', 'GCP_KMS', 'LOCAL_HSM', 'MANUAL', name='unsealprovidertype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_healthy', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('last_health_check', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auto_unseal_providers_name'), 'auto_unseal_providers', ['name'], unique=True)
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=True)
    op.create_table('shamir_shares',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('share_index', sa.Integer(), nullable=False),
    sa.Column('share_hash', sa.String(length=255), nullable=False),
    sa.Column('distributed_to', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vault_seal_state',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('SEALED', 'UNSEALED', name='sealstatus'), nullable=False),
    sa.Column('total_shares', sa.Integer(), nullable=False),
    sa.Column('threshold', sa.Integer(), nullable=False),
    sa.Column('shares_provided', sa.Integer(), nullable=False),
    sa.Column('encrypted_master_key', sa.Text(), nullable=True),
    sa.Column('unseal_provider', sa.String(length=64), nullable=True),
    sa.Column('sealed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unsealed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('initialized', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('namespaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['namespaces.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    op.create_index(op.f('ix_namespaces_org_id'), 'namespaces', ['org_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_org_id'), 'projects', ['org_id'], unique=False)
    op.create_index('ix_projects_org_name', 'projects', ['org_id', 'name'], unique=True)
    op.create_table('service_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('api_key_hash', sa.String(length=255), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('policy_ids', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key_hash')
    )
    op.create_index(op.f('ix_service_accounts_name'), 'service_accounts', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', 'SERVICE_ACCOUNT', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('ai_findings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='aifindingseverity'), nullable=False),
    sa.Column('confidence', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'INSUFFICIENT_EVIDENCE', name='aifindingconfidence'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ACKNOWLEDGED', 'INVESTIGATING', 'DISMISSED', 'RESOLVED', name='aifindingstatus'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.JSON(), nullable=False),
    sa.Column('recommended_actions', sa.JSON(), nullable=False),
    sa.Column('related_entities', sa.JSON(), nullable=True),
    sa.Column('ai_provider', sa.String(length=32), nullable=True),
    sa.Column('ai_model', sa.String(length=64), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.String(length=16), nullable=True),
    sa.Column('triggered_rules', sa.JSON(), nullable=True),
    sa.Column('correlated_event_ids', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_findings_category'), 'ai_findings', ['category'], unique=False)
    op.create_index(op.f('ix_ai_findings_severity'), 'ai_findings', ['severity'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Enum('USER_REGISTER', 'USER_LOGIN', 'USER_LOGOUT', 'USER_LOGIN_FAILED', 'TOKEN_REFRESH', 'MFA_ENABLED', 'MFA_DISABLED', 'MFA_VERIFIED', 'MFA_FAILED', 'VAULT_TOKEN_CREATE', 'VAULT_TOKEN_RENEW', 'VAULT_TOKEN_REVOKE', 'VAULT_TOKEN_LOOKUP', 'SECRET_CREATE', 'SECRET_READ', 'SECRET_UPDATE', 'SECRET_DELETE', 'SECRET_RESTORE', 'SECRET_PURGE', 'SECRET_ROLLBACK', 'SECRET_ROTATE', 'SECRET_ACCESS_DENIED', 'SECRET_VERSION_READ', 'DYNAMIC_CRED_GENERATE', 'DYNAMIC_CRED_REVOKE', 'LEASE_CREATE', 'LEASE_RENEW', 'LEASE_REVOKE', 'LEASE_EXPIRE', 'WRAP_CREATE', 'WRAP_UNWRAP', 'WRAP_EXPIRED', 'CUBBYHOLE_WRITE', 'CUBBYHOLE_READ', 'CUBBYHOLE_DELETE', 'POLICY_CREATE', 'POLICY_UPDATE', 'POLICY_DELETE', 'POLICY_ASSIGN', 'POLICY_REVOKE', 'ORG_CREATE', 'PROJECT_CREATE', 'TEAM_CREATE', 'NAMESPACE_CREATE', 'AI_ANALYSIS_RUN', 'AI_SEARCH_QUERY', 'AI_FINDING_CREATE', 'AI_FINDING_STATUS_CHANGE', name='auditaction'), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('namespace_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['namespace_id'], ['namespaces.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_user_action', 'audit_logs', ['user_id', 'action'], unique=False)
    op.create_table('benchmark_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('benchmark_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='benchmarkstatus'), nullable=False),
    sa.Column('results', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_benchmark_runs_benchmark_type'), 'benchmark_runs', ['benchmark_type'], unique=False)
    op.create_table('certificate_authorities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('ca_type', sa.Enum('ROOT_CA', 'INTERMEDIATE_CA', 'SERVER', 'CLIENT', 'MTLS', 'INTERNAL', name='certificatetype'), nullable=False),
    sa.Column('parent_ca_id', sa.UUID(), nullable=True),
    sa.Column('subject_dn', sa.Text(), nullable=False),
    sa.Column('certificate_pem', sa.Text(), nullable=False),
    sa.Column('encrypted_private_key', sa.Text(), nullable=False),
    sa.Column('serial_number', sa.String(length=128), nullable=False),
    sa.Column('not_before', sa.DateTime(timezone=True), nullable=False),
    sa.Column('not_after', sa.DateTime(timezone=True), nullable=False),
    sa.Column('key_algorithm', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('VALID', 'REVOKED', 'EXPIRED', 'PENDING', name='certificatestatus'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_ca_id'], ['certificate_authorities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_index(op.f('ix_certificate_authorities_name'), 'certificate_authorities', ['name'], unique=True)
    op.create_table('cubbyhole_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('vault_token_id', sa.String(length=255), nullable=True),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('encrypted_value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cubbyhole_entries_user_id'), 'cubbyhole_entries', ['user_id'], unique=False)
    op.create_index(op.f('ix_cubbyhole_entries_vault_token_id'), 'cubbyhole_entries', ['vault_token_id'], unique=False)
    op.create_index('ix_cubbyhole_user_key', 'cubbyhole_entries', ['user_id', 'key'], unique=True)
    op.create_table('demo_datasets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('loaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('records_created', sa.JSON(), nullable=False),
    sa.Column('loaded_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['loaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dynamic_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('credential_type', sa.Enum('DATABASE_POSTGRES', 'DATABASE_MYSQL', 'DATABASE_SQLITE', 'CLOUD_AWS', 'CLOUD_AZURE', 'CLOUD_GCP', 'APP_API_KEY', 'APP_ACCESS_TOKEN', name='credentialtype'), nullable=False),
    sa.Column('encrypted_credentials', sa.Text(), nullable=False),
    sa.Column('ttl_seconds', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dynamic_credentials_expires_at'), 'dynamic_credentials', ['expires_at'], unique=False)
    op.create_index(op.f('ix_dynamic_credentials_owner_id'), 'dynamic_credentials', ['owner_id'], unique=False)
    op.create_table('engine_mounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('engine_type', sa.String(length=64), nullable=False),
    sa.Column('mount_path', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ENABLED', 'DISABLED', 'MOUNTED', name='enginestatus'), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('namespace_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mounted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['namespace_id'], ['namespaces.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mount_path')
    )
    op.create_index(op.f('ix_engine_mounts_name'), 'engine_mounts', ['name'], unique=True)
    op.create_table('identity_providers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('provider_type', sa.Enum('OIDC', 'LDAP', 'ACTIVE_DIRECTORY', 'JWT', 'SAML', name='identityprovidertype'), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('group_mappings', sa.JSON(), nullable=True),
    sa.Column('role_mappings', sa.JSON(), nullable=True),
    sa.Column('namespace_mappings', sa.JSON(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_identity_providers_name'), 'identity_providers', ['name'], unique=True)
    op.create_table('mfa_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('totp_secret', sa.String(length=64), nullable=False),
    sa.Column('recovery_codes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('parent_policy_id', sa.UUID(), nullable=True),
    sa.Column('namespace_id', sa.UUID(), nullable=True),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['namespace_id'], ['namespaces.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_policy_id'], ['policies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policies_name'), 'policies', ['name'], unique=True)
    op.create_table('policy_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('format', sa.Enum('YAML', 'JSON', 'HCL', name='policyfileformat'), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_files_name'), 'policy_files', ['name'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('secrets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('namespace_id', sa.UUID(), nullable=True),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('encrypted_value', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DELETED', 'ARCHIVED', 'EXPIRED', name='secretstatus'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('encryption_algorithm', sa.String(length=32), nullable=False),
    sa.Column('key_version', sa.Integer(), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_delete_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rotation_enabled', sa.Boolean(), nullable=False),
    sa.Column('rotation_interval_days', sa.Integer(), nullable=True),
    sa.Column('last_rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_rotation_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('version >= 1', name='ck_secrets_version_positive'),
    sa.ForeignKeyConstraint(['namespace_id'], ['namespaces.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_secrets_category'), 'secrets', ['category'], unique=False)
    op.create_index('ix_secrets_expires_at', 'secrets', ['expires_at'], unique=False)
    op.create_index(op.f('ix_secrets_owner_id'), 'secrets', ['owner_id'], unique=False)
    op.create_index('ix_secrets_owner_key_active', 'secrets', ['owner_id', 'key'], unique=False, postgresql_where='is_deleted = false')
    op.create_index(op.f('ix_secrets_status'), 'secrets', ['status'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('policy_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_project_id'), 'teams', ['project_id'], unique=False)
    op.create_table('transit_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('key_type', sa.Enum('AES_256_GCM', 'CHACHA20_POLY1305', 'RSA_4096', 'ED25519', name='transitkeytype'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', 'DISABLED', 'DESTROYED', name='transitkeystatus'), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('min_decryption_version', sa.Integer(), nullable=False),
    sa.Column('exportable', sa.Boolean(), nullable=False),
    sa.Column('deletion_allowed', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('labels', sa.JSON(), nullable=True),
    sa.Column('rotation_policy_days', sa.Integer(), nullable=True),
    sa.Column('last_rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_rotation_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transit_keys_name'), 'transit_keys', ['name'], unique=True)
    op.create_table('vault_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token_id', sa.String(length=255), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('parent_token_id', sa.String(length=255), nullable=True),
    sa.Column('token_type', sa.Enum('SERVICE', 'BATCH', 'PERIODIC', 'ORPHAN', name='tokentype'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'REVOKED', name='tokenstatus'), nullable=False),
    sa.Column('policies', sa.JSON(), nullable=False),
    sa.Column('ttl_seconds', sa.Integer(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_renewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('renewal_count', sa.Integer(), nullable=False),
    sa.Column('max_renewals', sa.Integer(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_vault_tokens_expires_at'), 'vault_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_vault_tokens_token_id'), 'vault_tokens', ['token_id'], unique=True)
    op.create_index(op.f('ix_vault_tokens_user_id'), 'vault_tokens', ['user_id'], unique=False)
    op.create_table('wrapped_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('wrap_token', sa.String(length=255), nullable=False),
    sa.Column('wrap_token_hash', sa.String(length=255), nullable=False),
    sa.Column('encrypted_payload', sa.Text(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('ttl_seconds', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wrap_token_hash')
    )
    op.create_index(op.f('ix_wrapped_tokens_expires_at'), 'wrapped_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_wrapped_tokens_wrap_token'), 'wrapped_tokens', ['wrap_token'], unique=True)
    op.create_table('audit_replay_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('audit_log_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=True),
    sa.Column('resource', sa.String(length=255), nullable=True),
    sa.Column('namespace', sa.String(length=255), nullable=True),
    sa.Column('payload_summary', sa.JSON(), nullable=True),
    sa.Column('original_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audit_log_id'], ['audit_logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_replay_events_audit_log_id'), 'audit_replay_events', ['audit_log_id'], unique=False)
    op.create_index(op.f('ix_audit_replay_events_session_id'), 'audit_replay_events', ['session_id'], unique=False)
    op.create_index('ix_replay_events_session_seq', 'audit_replay_events', ['session_id', 'sequence'], unique=False)
    op.create_table('certificates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ca_id', sa.UUID(), nullable=False),
    sa.Column('cert_type', sa.Enum('ROOT_CA', 'INTERMEDIATE_CA', 'SERVER', 'CLIENT', 'MTLS', 'INTERNAL', name='certificatetype'), nullable=False),
    sa.Column('common_name', sa.String(length=255), nullable=False),
    sa.Column('subject_dn', sa.Text(), nullable=False),
    sa.Column('san_dns', sa.JSON(), nullable=True),
    sa.Column('san_ips', sa.JSON(), nullable=True),
    sa.Column('certificate_pem', sa.Text(), nullable=False),
    sa.Column('certificate_chain_pem', sa.Text(), nullable=True),
    sa.Column('csr_pem', sa.Text(), nullable=True),
    sa.Column('serial_number', sa.String(length=128), nullable=False),
    sa.Column('not_before', sa.DateTime(timezone=True), nullable=False),
    sa.Column('not_after', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('VALID', 'REVOKED', 'EXPIRED', 'PENDING', name='certificatestatus'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revocation_reason', sa.String(length=128), nullable=True),
    sa.Column('renewed_from_id', sa.UUID(), nullable=True),
    sa.Column('issued_to', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ca_id'], ['certificate_authorities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['renewed_from_id'], ['certificates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_index(op.f('ix_certificates_ca_id'), 'certificates', ['ca_id'], unique=False)
    op.create_index(op.f('ix_certificates_common_name'), 'certificates', ['common_name'], unique=False)
    op.create_index(op.f('ix_certificates_not_after'), 'certificates', ['not_after'], unique=False)
    op.create_table('leases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lease_id', sa.String(length=255), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('credential_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'REVOKED', 'RENEWED', name='leasestatus'), nullable=False),
    sa.Column('ttl_seconds', sa.Integer(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('renewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('renewal_count', sa.Integer(), nullable=False),
    sa.Column('max_renewals', sa.Integer(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['credential_id'], ['dynamic_credentials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leases_expires_at'), 'leases', ['expires_at'], unique=False)
    op.create_index(op.f('ix_leases_lease_id'), 'leases', ['lease_id'], unique=True)
    op.create_index(op.f('ix_leases_owner_id'), 'leases', ['owner_id'], unique=False)
    op.create_table('policy_file_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('policy_file_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('parsed_permissions', sa.JSON(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('validation_errors', sa.JSON(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['policy_file_id'], ['policy_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_policy_file_versions_file_ver', 'policy_file_versions', ['policy_file_id', 'version_number'], unique=True)
    op.create_index(op.f('ix_policy_file_versions_policy_file_id'), 'policy_file_versions', ['policy_file_id'], unique=False)
    op.create_table('policy_inheritance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_policy_id', sa.UUID(), nullable=False),
    sa.Column('child_policy_id', sa.UUID(), nullable=False),
    sa.Column('override', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['child_policy_id'], ['policies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_policy_id'], ['policies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_inheritance_child_policy_id'), 'policy_inheritance', ['child_policy_id'], unique=False)
    op.create_index('ix_policy_inheritance_pair', 'policy_inheritance', ['parent_policy_id', 'child_policy_id'], unique=True)
    op.create_index(op.f('ix_policy_inheritance_parent_policy_id'), 'policy_inheritance', ['parent_policy_id'], unique=False)
    op.create_table('rotation_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('secret_id', sa.UUID(), nullable=False),
    sa.Column('old_version', sa.Integer(), nullable=False),
    sa.Column('new_version', sa.Integer(), nullable=False),
    sa.Column('rotation_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', name='rotationstatus'), nullable=False),
    sa.Column('initiated_by', sa.UUID(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['initiated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['secret_id'], ['secrets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rotation_history_secret_id'), 'rotation_history', ['secret_id'], unique=False)
    op.create_table('secret_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('secret_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('encrypted_value', sa.Text(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('change_note', sa.Text(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['secret_id'], ['secrets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_secret_versions_secret_id'), 'secret_versions', ['secret_id'], unique=False)
    op.create_index('ix_secret_versions_secret_version', 'secret_versions', ['secret_id', 'version_number'], unique=True)
    op.create_table('team_members',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id', 'user_id')
    )
    op.create_table('transit_key_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('encrypted_key_material', sa.Text(), nullable=False),
    sa.Column('public_key_pem', sa.Text(), nullable=True),
    sa.Column('algorithm', sa.String(length=64), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('destroyed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['key_id'], ['transit_keys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transit_key_versions_key_id'), 'transit_key_versions', ['key_id'], unique=False)
    op.create_index('ix_transit_key_versions_key_ver', 'transit_key_versions', ['key_id', 'version_number'], unique=True)
    op.create_table('user_policies',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'policy_id')
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_policies')
    op.drop_index('ix_transit_key_versions_key_ver', table_name='transit_key_versions')
    op.drop_index(op.f('ix_transit_key_versions_key_id'), table_name='transit_key_versions')
    op.drop_table('transit_key_versions')
    op.drop_table('team_members')
    op.drop_index('ix_secret_versions_secret_version', table_name='secret_versions')
    op.drop_index(op.f('ix_secret_versions_secret_id'), table_name='secret_versions')
    op.drop_table('secret_versions')
    op.drop_index(op.f('ix_rotation_history_secret_id'), table_name='rotation_history')
    op.drop_table('rotation_history')
    op.drop_index(op.f('ix_policy_inheritance_parent_policy_id'), table_name='policy_inheritance')
    op.drop_index('ix_policy_inheritance_pair', table_name='policy_inheritance')
    op.drop_index(op.f('ix_policy_inheritance_child_policy_id'), table_name='policy_inheritance')
    op.drop_table('policy_inheritance')
    op.drop_index(op.f('ix_policy_file_versions_policy_file_id'), table_name='policy_file_versions')
    op.drop_index('ix_policy_file_versions_file_ver', table_name='policy_file_versions')
    op.drop_table('policy_file_versions')
    op.drop_index(op.f('ix_leases_owner_id'), table_name='leases')
    op.drop_index(op.f('ix_leases_lease_id'), table_name='leases')
    op.drop_index(op.f('ix_leases_expires_at'), table_name='leases')
    op.drop_table('leases')
    op.drop_index(op.f('ix_certificates_not_after'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_common_name'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_ca_id'), table_name='certificates')
    op.drop_table('certificates')
    op.drop_index('ix_replay_events_session_seq', table_name='audit_replay_events')
    op.drop_index(op.f('ix_audit_replay_events_session_id'), table_name='audit_replay_events')
    op.drop_index(op.f('ix_audit_replay_events_audit_log_id'), table_name='audit_replay_events')
    op.drop_table('audit_replay_events')
    op.drop_index(op.f('ix_wrapped_tokens_wrap_token'), table_name='wrapped_tokens')
    op.drop_index(op.f('ix_wrapped_tokens_expires_at'), table_name='wrapped_tokens')
    op.drop_table('wrapped_tokens')
    op.drop_index(op.f('ix_vault_tokens_user_id'), table_name='vault_tokens')
    op.drop_index(op.f('ix_vault_tokens_token_id'), table_name='vault_tokens')
    op.drop_index(op.f('ix_vault_tokens_expires_at'), table_name='vault_tokens')
    op.drop_table('vault_tokens')
    op.drop_index(op.f('ix_transit_keys_name'), table_name='transit_keys')
    op.drop_table('transit_keys')
    op.drop_index(op.f('ix_teams_project_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_secrets_status'), table_name='secrets')
    op.drop_index('ix_secrets_owner_key_active', table_name='secrets', postgresql_where='is_deleted = false')
    op.drop_index(op.f('ix_secrets_owner_id'), table_name='secrets')
    op.drop_index('ix_secrets_expires_at', table_name='secrets')
    op.drop_index(op.f('ix_secrets_category'), table_name='secrets')
    op.drop_table('secrets')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_policy_files_name'), table_name='policy_files')
    op.drop_table('policy_files')
    op.drop_index(op.f('ix_policies_name'), table_name='policies')
    op.drop_table('policies')
    op.drop_table('mfa_configs')
    op.drop_index(op.f('ix_identity_providers_name'), table_name='identity_providers')
    op.drop_table('identity_providers')
    op.drop_index(op.f('ix_engine_mounts_name'), table_name='engine_mounts')
    op.drop_table('engine_mounts')
    op.drop_index(op.f('ix_dynamic_credentials_owner_id'), table_name='dynamic_credentials')
    op.drop_index(op.f('ix_dynamic_credentials_expires_at'), table_name='dynamic_credentials')
    op.drop_table('dynamic_credentials')
    op.drop_table('demo_datasets')
    op.drop_index('ix_cubbyhole_user_key', table_name='cubbyhole_entries')
    op.drop_index(op.f('ix_cubbyhole_entries_vault_token_id'), table_name='cubbyhole_entries')
    op.drop_index(op.f('ix_cubbyhole_entries_user_id'), table_name='cubbyhole_entries')
    op.drop_table('cubbyhole_entries')
    op.drop_index(op.f('ix_certificate_authorities_name'), table_name='certificate_authorities')
    op.drop_table('certificate_authorities')
    op.drop_index(op.f('ix_benchmark_runs_benchmark_type'), table_name='benchmark_runs')
    op.drop_table('benchmark_runs')
    op.drop_index('ix_audit_logs_user_action', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_ai_findings_severity'), table_name='ai_findings')
    op.drop_index(op.f('ix_ai_findings_category'), table_name='ai_findings')
    op.drop_table('ai_findings')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_service_accounts_name'), table_name='service_accounts')
    op.drop_table('service_accounts')
    op.drop_index('ix_projects_org_name', table_name='projects')
    op.drop_index(op.f('ix_projects_org_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_namespaces_org_id'), table_name='namespaces')
    op.drop_table('namespaces')
    op.drop_table('vault_seal_state')
    op.drop_table('shamir_shares')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_auto_unseal_providers_name'), table_name='auto_unseal_providers')
    op.drop_table('auto_unseal_providers')
    # ### end Alembic commands ###
