#!/usr/bin/env python3
"""
Generate a production-ready .env file with secure random keys.
Run once: python scripts/generate_env.py
"""
import base64
import os
import secrets

SECRET_KEY = secrets.token_hex(32)
JWT_SECRET_KEY = secrets.token_hex(32)
ENCRYPTION_KEY = base64.b64encode(os.urandom(32)).decode()

env_content = f"""# Generated by scripts/generate_env.py — DO NOT COMMIT THIS FILE
APP_NAME=NanoVault
APP_ENV=production
DEBUG=false
SECRET_KEY={SECRET_KEY}
API_V1_PREFIX=/api/v1

JWT_SECRET_KEY={JWT_SECRET_KEY}
JWT_ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=30
REFRESH_TOKEN_EXPIRE_DAYS=7

DATABASE_URL=postgresql+asyncpg://nano_vault_user:nano_vault_pass@db:5432/nano_vault_db

ENCRYPTION_KEY={ENCRYPTION_KEY}

RATE_LIMIT_PER_MINUTE=60
AUTH_RATE_LIMIT_PER_MINUTE=10

ALLOWED_ORIGINS=http://localhost:3000
"""

with open(".env", "w") as f:
    f.write(env_content)

print("[+] .env written with fresh secrets.")
print(f"    SECRET_KEY      = {SECRET_KEY[:8]}...")
print(f"    JWT_SECRET_KEY  = {JWT_SECRET_KEY[:8]}...")
print(f"    ENCRYPTION_KEY  = {ENCRYPTION_KEY[:8]}...")
print("\n[!] Store ENCRYPTION_KEY in a secrets manager (AWS Secrets Manager, Vault, etc.)")
print("[!] Losing ENCRYPTION_KEY = permanent loss of all encrypted secrets.")
